spring:
  application:
    name: wang-ai-code-generator-backend

server:
  port: 8124
  servlet:
    context-path: /api


# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.wang.wangaicodegenerator.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn


