spring:
  application:
    name: wang-ai-code-generator-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wang_ai_code_generator
    username: root
    password: 123456

server:
  port: 8124
  servlet:
    context-path: /api


# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.wang.wangaicodegenerator.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn



